-- Create BCDA tables in RAW schema

CREATE TABLE IF NOT EXISTS DEV_DB.RAW.RAW_BCDA_PATIENT (
    DATA VARIANT
);

CREATE TABLE IF NOT EXISTS DEV_DB.RAW.RAW_BCDA_EXPLANATION_OF_BENEFIT (
    DATA VARIANT
);

CREATE TABLE IF NOT EXISTS DEV_DB.RAW.RAW_BCDA_COVERAGE (
    DATA VARIANT
);

-- Show tables created
SHOW TABLES LIKE 'RAW_BCDA%' IN DEV_DB.RAW;
