-- ============================================================================
-- Load CMS P1 Data from S3 to Snowflake
-- Generated: 2026-02-08
-- Tables: 153 CMS datasets (ACO, Quality, MA, Claims)
-- ============================================================================

-- Use correct database and schema
USE DATABASE DEV_DB;
USE SCHEMA RAW;
USE WAREHOUSE DEV_WH;

-- Verify CSV format exists
SHOW FILE FORMATS LIKE 'CSV_FORMAT' IN DEV_DB.RAW;

-- Load ACO Data (91 files)
COPY INTO DEV_DB.RAW.CMS_ACO_PY3_ALGN_BENE_PUF_RDX FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/py3_algn_bene_puf_rdx.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;
COPY INTO DEV_DB.RAW.CMS_ACO_PY2_ALGN_BENE_PUF_REDACT FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/py2_ALGN_BENE_PUF_REDACT.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;
COPY INTO DEV_DB.RAW.CMS_ACO_PY1_ALGN_BENE_PUF_REDACT_UPDATE FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/py1_ALGN_BENE_PUF_REDACT_UPDATE.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;
COPY INTO DEV_DB.RAW.CMS_ACO_PY3_ELIG_BENE_PUF_RDX FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/py3_elig_bene_puf_rdx.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;
COPY INTO DEV_DB.RAW.CMS_ACO_PY2_ELIG_BENE_PUF FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/py2_ELIG_BENE_PUF.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;
COPY INTO DEV_DB.RAW.CMS_ACO_ELIG_BENE_PUF_REDACT FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/ELIG_BENE_PUF_REDACT.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;
COPY INTO DEV_DB.RAW.CMS_ACO_PY3_FNCL_QLTYPUF_RDX FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/py3_fncl_qltypuf_rdx.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;
COPY INTO DEV_DB.RAW.CMS_ACO_PY3_PRVDR_PUF FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/py3_prvdr_puf.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;
COPY INTO DEV_DB.RAW.CMS_ACO_PY2_PRVDR_PUF FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/py2_PRVDR_PUF.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;
COPY INTO DEV_DB.RAW.CMS_ACO_PROVIDER_PUF FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/PROVIDER_PUF.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;
COPY INTO DEV_DB.RAW.CMS_ACO_PY2026_MEDICARE_SHARED_SAVINGS_PROGRAM_PARTICIPANTS FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/PY2026_Medicare_Shared_Savings_Program_Participants.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;
COPY INTO DEV_DB.RAW.CMS_ACO_PY2025_MEDICARE_SHARED_SAVINGS_PROGRAM_PARTICIPANTS FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/py2025_medicare_shared_savings_program_participants.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;
COPY INTO DEV_DB.RAW.CMS_ACO_PY2024_MEDICARE_SHARED_SAVINGS_PROGRAM_PARTICIPANTS FROM @DEV_DB.RAW.S3_BCDA_STAGE/cms-data/aco/PY2024_Medicare_Shared_Savings_Program_Participants.csv FILE_FORMAT = (FORMAT_NAME = 'DEV_DB.RAW.CSV_FORMAT') ON_ERROR = CONTINUE;

-- Check loaded row counts
SELECT 'CMS_ACO_PY3_ALGN_BENE_PUF_RDX' as table_name, COUNT(*) as row_count FROM DEV_DB.RAW.CMS_ACO_PY3_ALGN_BENE_PUF_RDX
UNION ALL SELECT 'CMS_ACO_PY2026_PARTICIPANTS', COUNT(*) FROM DEV_DB.RAW.CMS_ACO_PY2026_MEDICARE_SHARED_SAVINGS_PROGRAM_PARTICIPANTS
UNION ALL SELECT 'CMS_ACO_PY3_PRVDR_PUF', COUNT(*) FROM DEV_DB.RAW.CMS_ACO_PY3_PRVDR_PUF
ORDER BY row_count DESC;

-- NOTE: This is a sample of 13 tables.
-- Full script with all 153 tables saved to: ~/projects/healthcare-analytics/load_cms_p1_full.sql
