-- Truncate tables first
TRUNCATE TABLE DEV_DB.RAW.RAW_BCDA_PATIENT;
TRUNCATE TABLE DEV_DB.RAW.RAW_BCDA_EXPLANATION_OF_BENEFIT;
TRUNCATE TABLE DEV_DB.RAW.RAW_BCDA_COVERAGE;

-- Load BCDA Patient data
COPY INTO DEV_DB.RAW.RAW_BCDA_PATIENT
FROM @DEV_DB.RAW.S3_BCDA_STAGE/bcda/patients/
FILE_FORMAT = (TYPE = 'JSON', STRIP_OUTER_ARRAY = FALSE)
ON_ERROR = CONTINUE;

-- Load BCDA ExplanationOfBenefit data
COPY INTO DEV_DB.RAW.RAW_BCDA_EXPLANATION_OF_BENEFIT
FROM @DEV_DB.RAW.S3_BCDA_STAGE/bcda/eob/
FILE_FORMAT = (TYPE = 'JSON', STRIP_OUTER_ARRAY = FALSE)
ON_ERROR = CONTINUE;

-- Load BCDA Coverage data
COPY INTO DEV_DB.RAW.RAW_BCDA_COVERAGE
FROM @DEV_DB.RAW.S3_BCDA_STAGE/bcda/coverage/
FILE_FORMAT = (TYPE = 'JSON', STRIP_OUTER_ARRAY = FALSE)
ON_ERROR = CONTINUE;

-- Show row counts
SELECT 'RAW_BCDA_PATIENT' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM DEV_DB.RAW.RAW_BCDA_PATIENT
UNION ALL
SELECT 'RAW_BCDA_EXPLANATION_OF_BENEFIT', COUNT(*) FROM DEV_DB.RAW.RAW_BCDA_EXPLANATION_OF_BENEFIT
UNION ALL
SELECT 'RAW_BCDA_COVERAGE', COUNT(*) FROM DEV_DB.RAW.RAW_BCDA_COVERAGE;
